$ANSIBLE_VAULT;1.1;AES256
35653335616165373438616234383438383565613135623434393636363565616238386263613262
3434613830633935646437313762383037613530643865310a616638343938613139666633613263
62363437643666663864646432666533613634323036316263616239636437613631393364326430
6434333865306339660a626534343037623266393231643566303932316362636332633461656436
65663866626264623164306230363361623835343261323462613134346561663534383036613765
30306637653966323631383461313031303461353331323133663430636131323635306137623161
30666336636438393639346339643637616135356466303330303864303538633537636139396334
37333632626239353931303238376362636437386137326630373032363730383965366631326665
65663433323062333036313766363235316637326438663230353831366430333865313364663262
61383436323464353832306631616533663262353233373139366335306462613162313463393863
30613963656232646166363136626536623562666262646634653235393534666163363631616131
36366538396364666339313639333530383961653566636439663931363235323138356335646664
3866
