$ANSIBLE_VAULT;1.1;AES256
38336132353035343631653464326665616635363064623564613030383231633135376264306634
6233303232383865303265363261356632383237373861370a343433333839356534323738646666
66613065346138356261346362343436366231613131336531653436356363613339643831663836
3936366331323537370a316639333639646434323937303937626132363730363136613336313763
61346432323133326665653562663161633661653730613930303133333362643837393636383235
34333738343261346362616239656264393262343731656566323233316262303866653530393839
63336536366138633833383534656430373165663439643464376439666337616331343565646363
61636261383531623535353964626435376336633234343134373865613437363231623839303964
34356133326664616564623538366536313334626664613939343366326263613334383132383536
30303334336432353238333231323935313932633562383232303366343466303034613933643964
35306637663431363932353338633163363966636366366438336431666631363134373964643731
62333761616334323562
