$ANSIBLE_VAULT;1.1;AES256
64636537333733333534343232376661636637316432303630633938366137346563636139373566
6136646439623465353062613638633333633833663738390a636563323032323332366162653634
35623963363431376437346333613030313235333533663339373961393233333037326432373564
3461613837613563380a623830373435643235333138306164343030623530313735623163376236
30396430623866656231316661353930396634616463346564663334636236666530373963663263
63353834643132316238666366613339366462376565306663396531356538383237326163626666
39353036633738326462336335663331623162376635336362666664613937663865613737376432
39663966396138393564646363643962353661636434313237353030663764376130333834643039
65373232386136373339363564656162386537353632356535393466663039366338613530383361
3264616163333763346636626636636631616535613939663036
