$ANSIBLE_VAULT;1.1;AES256
61643865633839356635366563643434356662313236623636616435306330393537323131626461
3261313738323132306235663637626330636630383230340a316439653831616239316363313434
33353630383866626461356163636261333662396332393136336137323164363236386337313937
3162323638346662610a633865636661366530626633633065663832326234356564386438306261
34663064373662666138343465373831373635346538346532663834363230313865653964613532
62366462316639393932353761346638376661363936663335666366363462656566353239343361
38346164366236643938303932633962663836633436363133636438653266643564363362313530
36393433356662333262623664646232653437373961616632326534653131613132336331373163
36316530646231656239346137636232386134323130333632303137356137323666373761663662
32343739383563383431383338396333646331373431376162383536323534643539646362336339
33373765666634633939303664613663666666303761646130326535366139656566623763653830
37313938326231646230303630383130633139646138633335313338613239306136323830373435
35616638643165323638393963616136666235653363383361306135366362303530393363373038
6238353362393639353865353738643230383634383030613432
