$ANSIBLE_VAULT;1.1;AES256
35373731666438323066373934303338663834323031623962343831623733393663346532316133
6137633963666537306430323662363166636465633761610a666230376431336665643534656432
62336434616330363232356165363961316530383834326239653936653537643166356436666233
3039353531356632350a383036363537303364313735653330303361363964386439326462303532
62383464336336316666663332313538653530376536393130653633316339323430316635306461
63643033646162383436633937383634616637653862376366353936623539363230303136386233
34623561303661313732363864663261646562616665653036336635646532643135343939666234
36323038323333656366643337646262353537353230383862613036613465656566616465623937
31666130613632393037323333376239663836623036643166386432386466393566333135633164
6434343461306633333535303865346531656135643733363566
